// Generated from CLDR common/supplemental/windowsZones.xml (unicode-org/cldr,
// Unicode License v3): IANA time zone -> Windows time zone ID for tzutil.
// ignore_for_file: lines_longer_than_80_chars

const windowsZonesByIana = <String, List<String>>{
  'AUS Central Standard Time': <String>['Australia/Darwin'],
  'AUS Eastern Standard Time': <String>[
    'Australia/Melbourne',
    'Australia/Sydney'
  ],
  'Afghanistan Standard Time': <String>['Asia/Kabul'],
  'Alaskan Standard Time': <String>[
    'America/Anchorage',
    'America/Juneau',
    'America/Metlakatla',
    'America/Nome',
    'America/Sitka',
    'America/Yakutat'
  ],
  'Aleutian Standard Time': <String>['America/Adak'],
  'Altai Standard Time': <String>['Asia/Barnaul'],
  'Arab Standard Time': <String>[
    'Asia/Aden',
    'Asia/Bahrain',
    'Asia/Kuwait',
    'Asia/Qatar',
    'Asia/Riyadh'
  ],
  'Arabian Standard Time': <String>['Asia/Dubai', 'Asia/Muscat'],
  'Arabic Standard Time': <String>['Asia/Baghdad'],
  'Argentina Standard Time': <String>[
    'America/Argentina/La_Rioja',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Salta',
    'America/Argentina/San_Juan',
    'America/Argentina/San_Luis',
    'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia',
    'America/Buenos_Aires',
    'America/Catamarca',
    'America/Cordoba',
    'America/Jujuy',
    'America/Mendoza'
  ],
  'Astrakhan Standard Time': <String>['Europe/Astrakhan', 'Europe/Ulyanovsk'],
  'Atlantic Standard Time': <String>[
    'America/Glace_Bay',
    'America/Goose_Bay',
    'America/Halifax',
    'America/Moncton',
    'America/Thule',
    'Atlantic/Bermuda'
  ],
  'Aus Central W. Standard Time': <String>['Australia/Eucla'],
  'Azerbaijan Standard Time': <String>['Asia/Baku'],
  'Azores Standard Time': <String>['America/Scoresbysund', 'Atlantic/Azores'],
  'Bahia Standard Time': <String>['America/Bahia'],
  'Bangladesh Standard Time': <String>['Asia/Dhaka', 'Asia/Thimphu'],
  'Belarus Standard Time': <String>['Europe/Minsk'],
  'Bougainville Standard Time': <String>['Pacific/Bougainville'],
  'Canada Central Standard Time': <String>[
    'America/Regina',
    'America/Swift_Current'
  ],
  'Cape Verde Standard Time': <String>['Atlantic/Cape_Verde'],
  'Caucasus Standard Time': <String>['Asia/Yerevan'],
  'Cen. Australia Standard Time': <String>[
    'Australia/Adelaide',
    'Australia/Broken_Hill'
  ],
  'Central America Standard Time': <String>[
    'America/Belize',
    'America/Costa_Rica',
    'America/El_Salvador',
    'America/Guatemala',
    'America/Managua',
    'America/Tegucigalpa',
    'Pacific/Galapagos'
  ],
  'Central Asia Standard Time': <String>[
    'Antarctica/Vostok',
    'Asia/Bishkek',
    'Asia/Urumqi',
    'Indian/Chagos'
  ],
  'Central Brazilian Standard Time': <String>[
    'America/Campo_Grande',
    'America/Cuiaba'
  ],
  'Central Europe Standard Time': <String>[
    'Europe/Belgrade',
    'Europe/Bratislava',
    'Europe/Budapest',
    'Europe/Ljubljana',
    'Europe/Podgorica',
    'Europe/Prague',
    'Europe/Tirane'
  ],
  'Central European Standard Time': <String>[
    'Europe/Sarajevo',
    'Europe/Skopje',
    'Europe/Warsaw',
    'Europe/Zagreb'
  ],
  'Central Pacific Standard Time': <String>[
    'Antarctica/Casey',
    'Pacific/Efate',
    'Pacific/Guadalcanal',
    'Pacific/Kosrae',
    'Pacific/Noumea',
    'Pacific/Ponape'
  ],
  'Central Standard Time': <String>[
    'America/Chicago',
    'America/Indiana/Knox',
    'America/Indiana/Tell_City',
    'America/Matamoros',
    'America/Menominee',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Ojinaga',
    'America/Rankin_Inlet',
    'America/Resolute',
    'America/Winnipeg'
  ],
  'Central Standard Time (Mexico)': <String>[
    'America/Bahia_Banderas',
    'America/Chihuahua',
    'America/Merida',
    'America/Mexico_City',
    'America/Monterrey'
  ],
  'Chatham Islands Standard Time': <String>['Pacific/Chatham'],
  'China Standard Time': <String>[
    'Asia/Hong_Kong',
    'Asia/Macau',
    'Asia/Shanghai'
  ],
  'Cuba Standard Time': <String>['America/Havana'],
  'E. Africa Standard Time': <String>[
    'Africa/Addis_Ababa',
    'Africa/Asmera',
    'Africa/Dar_es_Salaam',
    'Africa/Djibouti',
    'Africa/Kampala',
    'Africa/Mogadishu',
    'Africa/Nairobi',
    'Antarctica/Syowa',
    'Indian/Antananarivo',
    'Indian/Comoro',
    'Indian/Mayotte'
  ],
  'E. Australia Standard Time': <String>[
    'Australia/Brisbane',
    'Australia/Lindeman'
  ],
  'E. Europe Standard Time': <String>['Europe/Chisinau'],
  'E. South America Standard Time': <String>['America/Sao_Paulo'],
  'Easter Island Standard Time': <String>['Pacific/Easter'],
  'Eastern Standard Time': <String>[
    'America/Detroit',
    'America/Indiana/Petersburg',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Iqaluit',
    'America/Kentucky/Monticello',
    'America/Louisville',
    'America/Nassau',
    'America/New_York',
    'America/Toronto'
  ],
  'Eastern Standard Time (Mexico)': <String>['America/Cancun'],
  'Egypt Standard Time': <String>['Africa/Cairo'],
  'Ekaterinburg Standard Time': <String>['Asia/Yekaterinburg'],
  'FLE Standard Time': <String>[
    'Europe/Helsinki',
    'Europe/Kiev',
    'Europe/Mariehamn',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Vilnius'
  ],
  'Fiji Standard Time': <String>['Pacific/Fiji'],
  'GMT Standard Time': <String>[
    'Atlantic/Canary',
    'Atlantic/Faeroe',
    'Atlantic/Madeira',
    'Europe/Dublin',
    'Europe/Guernsey',
    'Europe/Isle_of_Man',
    'Europe/Jersey',
    'Europe/Lisbon',
    'Europe/London'
  ],
  'GTB Standard Time': <String>[
    'Asia/Famagusta',
    'Asia/Nicosia',
    'Europe/Athens',
    'Europe/Bucharest'
  ],
  'Georgian Standard Time': <String>['Asia/Tbilisi'],
  'Greenland Standard Time': <String>['America/Godthab'],
  'Greenwich Standard Time': <String>[
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Bamako',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Conakry',
    'Africa/Dakar',
    'Africa/Freetown',
    'Africa/Lome',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Ouagadougou',
    'America/Danmarkshavn',
    'Atlantic/Reykjavik',
    'Atlantic/St_Helena'
  ],
  'Haiti Standard Time': <String>['America/Port-au-Prince'],
  'Hawaiian Standard Time': <String>[
    'Pacific/Honolulu',
    'Pacific/Rarotonga',
    'Pacific/Tahiti'
  ],
  'India Standard Time': <String>['Asia/Calcutta'],
  'Iran Standard Time': <String>['Asia/Tehran'],
  'Israel Standard Time': <String>['Asia/Jerusalem'],
  'Jordan Standard Time': <String>['Asia/Amman'],
  'Kaliningrad Standard Time': <String>['Europe/Kaliningrad'],
  'Korea Standard Time': <String>['Asia/Seoul'],
  'Libya Standard Time': <String>['Africa/Tripoli'],
  'Line Islands Standard Time': <String>['Pacific/Kiritimati'],
  'Lord Howe Standard Time': <String>['Australia/Lord_Howe'],
  'Magadan Standard Time': <String>['Asia/Magadan'],
  'Magallanes Standard Time': <String>[
    'America/Coyhaique',
    'America/Punta_Arenas'
  ],
  'Marquesas Standard Time': <String>['Pacific/Marquesas'],
  'Mauritius Standard Time': <String>[
    'Indian/Mahe',
    'Indian/Mauritius',
    'Indian/Reunion'
  ],
  'Middle East Standard Time': <String>['Asia/Beirut'],
  'Montevideo Standard Time': <String>['America/Montevideo'],
  'Morocco Standard Time': <String>['Africa/Casablanca', 'Africa/El_Aaiun'],
  'Mountain Standard Time': <String>[
    'America/Boise',
    'America/Cambridge_Bay',
    'America/Ciudad_Juarez',
    'America/Denver',
    'America/Edmonton',
    'America/Inuvik'
  ],
  'Mountain Standard Time (Mexico)': <String>['America/Mazatlan'],
  'Myanmar Standard Time': <String>['Asia/Rangoon', 'Indian/Cocos'],
  'N. Central Asia Standard Time': <String>['Asia/Novosibirsk'],
  'Namibia Standard Time': <String>['Africa/Windhoek'],
  'Nepal Standard Time': <String>['Asia/Katmandu'],
  'New Zealand Standard Time': <String>[
    'Antarctica/McMurdo',
    'Pacific/Auckland'
  ],
  'Newfoundland Standard Time': <String>['America/St_Johns'],
  'Norfolk Standard Time': <String>['Pacific/Norfolk'],
  'North Asia East Standard Time': <String>['Asia/Irkutsk'],
  'North Asia Standard Time': <String>['Asia/Krasnoyarsk', 'Asia/Novokuznetsk'],
  'North Korea Standard Time': <String>['Asia/Pyongyang'],
  'Omsk Standard Time': <String>['Asia/Omsk'],
  'Pacific SA Standard Time': <String>['America/Santiago'],
  'Pacific Standard Time': <String>['America/Los_Angeles', 'America/Vancouver'],
  'Pacific Standard Time (Mexico)': <String>['America/Tijuana'],
  'Pakistan Standard Time': <String>['Asia/Karachi'],
  'Paraguay Standard Time': <String>['America/Asuncion'],
  'Qyzylorda Standard Time': <String>['Asia/Qyzylorda'],
  'Romance Standard Time': <String>[
    'Africa/Ceuta',
    'Europe/Brussels',
    'Europe/Copenhagen',
    'Europe/Madrid',
    'Europe/Paris'
  ],
  'Russia Time Zone 10': <String>['Asia/Srednekolymsk'],
  'Russia Time Zone 11': <String>['Asia/Anadyr', 'Asia/Kamchatka'],
  'Russia Time Zone 3': <String>['Europe/Samara'],
  'Russian Standard Time': <String>[
    'Europe/Kirov',
    'Europe/Moscow',
    'Europe/Simferopol'
  ],
  'SA Eastern Standard Time': <String>[
    'America/Belem',
    'America/Cayenne',
    'America/Fortaleza',
    'America/Maceio',
    'America/Paramaribo',
    'America/Recife',
    'America/Santarem',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Atlantic/Stanley'
  ],
  'SA Pacific Standard Time': <String>[
    'America/Bogota',
    'America/Cayman',
    'America/Coral_Harbour',
    'America/Eirunepe',
    'America/Guayaquil',
    'America/Jamaica',
    'America/Lima',
    'America/Panama',
    'America/Rio_Branco'
  ],
  'SA Western Standard Time': <String>[
    'America/Anguilla',
    'America/Antigua',
    'America/Aruba',
    'America/Barbados',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Curacao',
    'America/Dominica',
    'America/Grenada',
    'America/Guadeloupe',
    'America/Guyana',
    'America/Kralendijk',
    'America/La_Paz',
    'America/Lower_Princes',
    'America/Manaus',
    'America/Marigot',
    'America/Martinique',
    'America/Montserrat',
    'America/Port_of_Spain',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Santo_Domingo',
    'America/St_Barthelemy',
    'America/St_Kitts',
    'America/St_Lucia',
    'America/St_Thomas',
    'America/St_Vincent',
    'America/Tortola'
  ],
  'SE Asia Standard Time': <String>[
    'Antarctica/Davis',
    'Asia/Bangkok',
    'Asia/Jakarta',
    'Asia/Phnom_Penh',
    'Asia/Pontianak',
    'Asia/Saigon',
    'Asia/Vientiane',
    'Indian/Christmas'
  ],
  'Saint Pierre Standard Time': <String>['America/Miquelon'],
  'Sakhalin Standard Time': <String>['Asia/Sakhalin'],
  'Samoa Standard Time': <String>['Pacific/Apia'],
  'Sao Tome Standard Time': <String>['Africa/Sao_Tome'],
  'Saratov Standard Time': <String>['Europe/Saratov'],
  'Singapore Standard Time': <String>[
    'Asia/Brunei',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Singapore'
  ],
  'South Africa Standard Time': <String>[
    'Africa/Blantyre',
    'Africa/Bujumbura',
    'Africa/Gaborone',
    'Africa/Harare',
    'Africa/Johannesburg',
    'Africa/Kigali',
    'Africa/Lubumbashi',
    'Africa/Lusaka',
    'Africa/Maputo',
    'Africa/Maseru',
    'Africa/Mbabane'
  ],
  'South Sudan Standard Time': <String>['Africa/Juba'],
  'Sri Lanka Standard Time': <String>['Asia/Colombo'],
  'Sudan Standard Time': <String>['Africa/Khartoum'],
  'Syria Standard Time': <String>['Asia/Damascus'],
  'Taipei Standard Time': <String>['Asia/Taipei'],
  'Tasmania Standard Time': <String>[
    'Antarctica/Macquarie',
    'Australia/Hobart'
  ],
  'Tocantins Standard Time': <String>['America/Araguaina'],
  'Tokyo Standard Time': <String>[
    'Asia/Dili',
    'Asia/Jayapura',
    'Asia/Tokyo',
    'Pacific/Palau'
  ],
  'Tomsk Standard Time': <String>['Asia/Tomsk'],
  'Tonga Standard Time': <String>['Pacific/Tongatapu'],
  'Transbaikal Standard Time': <String>['Asia/Chita'],
  'Turkey Standard Time': <String>['Europe/Istanbul'],
  'Turks And Caicos Standard Time': <String>['America/Grand_Turk'],
  'US Eastern Standard Time': <String>[
    'America/Indiana/Marengo',
    'America/Indiana/Vevay',
    'America/Indianapolis'
  ],
  'US Mountain Standard Time': <String>[
    'America/Creston',
    'America/Dawson_Creek',
    'America/Fort_Nelson',
    'America/Hermosillo',
    'America/Phoenix'
  ],
  'UTC+12': <String>[
    'Pacific/Funafuti',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Nauru',
    'Pacific/Tarawa',
    'Pacific/Wake',
    'Pacific/Wallis'
  ],
  'UTC+13': <String>['Pacific/Enderbury', 'Pacific/Fakaofo'],
  'UTC-02': <String>['America/Noronha', 'Atlantic/South_Georgia'],
  'UTC-08': <String>['Pacific/Pitcairn'],
  'UTC-09': <String>['Pacific/Gambier'],
  'UTC-11': <String>['Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
  'Ulaanbaatar Standard Time': <String>['Asia/Ulaanbaatar'],
  'Venezuela Standard Time': <String>['America/Caracas'],
  'Vladivostok Standard Time': <String>['Asia/Ust-Nera', 'Asia/Vladivostok'],
  'Volgograd Standard Time': <String>['Europe/Volgograd'],
  'W. Australia Standard Time': <String>['Australia/Perth'],
  'W. Central Africa Standard Time': <String>[
    'Africa/Algiers',
    'Africa/Bangui',
    'Africa/Brazzaville',
    'Africa/Douala',
    'Africa/Kinshasa',
    'Africa/Lagos',
    'Africa/Libreville',
    'Africa/Luanda',
    'Africa/Malabo',
    'Africa/Ndjamena',
    'Africa/Niamey',
    'Africa/Porto-Novo',
    'Africa/Tunis'
  ],
  'W. Europe Standard Time': <String>[
    'Arctic/Longyearbyen',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Berlin',
    'Europe/Busingen',
    'Europe/Gibraltar',
    'Europe/Luxembourg',
    'Europe/Malta',
    'Europe/Monaco',
    'Europe/Oslo',
    'Europe/Rome',
    'Europe/San_Marino',
    'Europe/Stockholm',
    'Europe/Vaduz',
    'Europe/Vatican',
    'Europe/Vienna',
    'Europe/Zurich'
  ],
  'W. Mongolia Standard Time': <String>['Asia/Hovd'],
  'West Asia Standard Time': <String>[
    'Antarctica/Mawson',
    'Asia/Almaty',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Atyrau',
    'Asia/Dushanbe',
    'Asia/Oral',
    'Asia/Qostanay',
    'Asia/Samarkand',
    'Asia/Tashkent',
    'Indian/Kerguelen',
    'Indian/Maldives'
  ],
  'West Bank Standard Time': <String>['Asia/Gaza', 'Asia/Hebron'],
  'West Pacific Standard Time': <String>[
    'Antarctica/DumontDUrville',
    'Pacific/Guam',
    'Pacific/Port_Moresby',
    'Pacific/Saipan',
    'Pacific/Truk'
  ],
  'Yakutsk Standard Time': <String>['Asia/Khandyga', 'Asia/Yakutsk'],
  'Yukon Standard Time': <String>['America/Dawson', 'America/Whitehorse'],
};
